# Generated by Django 4.0.2 on 2022-02-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='skladniki',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='nazwa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
